import { Activity, ActivityType } from "../types";

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '1',
    title: 'Introduction to Machine Learning',
    type: ActivityType.CLASS,
    category: 'Machine Learning',
    instructor: 'Dr Nagaraju',
    progress: 40,
    durationLeft: '2 hrs left',
  },
  {
    id: '2',
    title: 'Neural Networks Quiz',
    type: ActivityType.QUIZ,
    category: 'AI',
    dueDate: 'Due tomorrow, 11:59 PM',
    status: 'PENDING',
  },
  {
    id: '3',
    title: 'Deep Learning Fundamentals',
    type: ActivityType.CLASS,
    category: 'AI',
    instructor: 'Prof. Gopika',
    progress: 75,
    durationLeft: '1 hr left',
  },
  {
    id: '4',
    title: 'Cloud Architecture Assignment',
    type: ActivityType.ASSIGNMENT,
    category: 'Cloud Computing',
    dueDate: 'Due Friday, Jan 23',
    status: 'PENDING',
  },
  {
    id: '5',
    title: 'AWS Services Overview',
    type: ActivityType.CLASS,
    category: 'Cloud Computing',
    instructor: 'Dr. Virat kohli',
    progress: 60,
    durationLeft: '3 hrs left',
  },
  {
    id: '6',
    title: 'Supervised Learning Quiz',
    type: ActivityType.QUIZ,
    category: 'Machine Learning',
    dueDate: 'Due tomorrow, 11:59 PM',
    status: 'COMPLETED',
  },
  {
    id: '7',
    title: 'Natural Language Processing',
    type: ActivityType.CLASS,
    category: 'AI',
    instructor: 'Dr Mallama',
    progress: 20,
    durationLeft: '4 hrs left',
  },
  {
    id: '8',
    title: 'Kubernetes Deployment Assignment',
    type: ActivityType.ASSIGNMENT,
    category: 'Cloud Computing',
    dueDate: 'Due tomorrow, 11:59 PM',
    status: 'PENDING',
  },
  {
    id: '9',
    title: 'Computer Vision Basics',
    type: ActivityType.CLASS,
    category: 'AI',
    instructor: 'Prof. Raju',
    progress: 85,
    durationLeft: '30 mins left',
  },
  {
    id: '10',
    title: 'ML Algorithms Quiz',
    type: ActivityType.QUIZ,
    category: 'Machine Learning',
    dueDate: 'Due Friday, Jan 23',
    status: 'PENDING',
  },
];
